### PR TITLE
Styling pages with css

### PR DESCRIPTION
**Pull request by irozag**
styling font sizes and font families, along with page wide layout

### CODE REVIEW

**Comment by epidrome** [comment]
what is the difference in comparison to #150 ?

both PRs contain the same files (some of them not needed)

there are some new css files, are these yours or from another origin, please explain or provide links

**Comment by irozag** [comment]
this branch continued from the #150 so it includes all the commits of the previous branch. Here I follow the styling manual of jekills and minimal mistakes. 

https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/
https://mmistakes.github.io/minimal-mistakes/docs/layouts/#wide-page

my report (on progress) 
https://github.com/irozg/iv/blob/1088747/reports/1088747/README.md

**Comment by epidrome** [comment]
are the minimal-mistakes css files edited by you or are they vanilla?

**Comment by irozag** [comment]
they are vanila, the minimal-mistakes files in scss folder is just a copy that jekylls need to read the overrides. The overrides are in the main.scss file in assets/ css folder

**Comment by epidrome** [comment]
unmodified files are not needed here, because they are included automatically through jekyll-remote-theme

**Comment by irozag** [comment]
It doesn't worked when I tested. Also there is a reference 

https://mmistakes.github.io/minimal-mistakes/docs/stylesheets/
"**Note**: To make more extensive changes and customize the Sass partials bundled in the gem. You will need to copy the complete contents of the _sass directory to <your_project> due to the way Jekyll currently reads those files."

**Comment by epidrome** [comment]
ok, you are right! still, i am skeptical, do we want to take on the burden of keeping in sync future changes to those (copy-pasted) files? 

are you changes so critical?

**Comment by irozag** [comment]
It's not so critical, it's just an aesthetic addition.

**Pull request closed without merging**
